### ISSUE TITLE
OCR0064: Experiment with OCR model to run inference

### ISSUE THREAD

**Issue by 10kalden** [OpenPecha/find-hard-negatives#4]
**Description:**
We have several OCR models on BDRC huggingface [here](https://huggingface.co/BDRC). We must experiment with running inference by loading the model locally or creating an API.

**Implementation:**
1. We start by taking one model for inference(woodblock) and experimenting with that.
2. Load the models locally and run the inference
3. Explore deploying the model and creating API.

**Subtask:**
- [x]  Run the model locally.
- [x]  Deploy the model and create API for inference.
- [x]  Write script for inference 

**Completion Criteria:**
To develop a method to run inference on a model

**Card Reviewer**

- [x] @ta4tsering

**Comment by ta4tsering** [comment]
Use this repo to see the OCR-Deployment Scripts that is available there at the https://github.com/OpenPecha/OCR-Deployment/tree/API
And you can make changes to the repo with a new branch if you want.
